### ISSUE TITLE
A proper guide to add as a Gradle dependency

### ISSUE THREAD

**Issue by kevintanhongann** [rlovtangen/grails-wkhtmltopdf#13]

**Comment by rlovtangen** [comment]
Do you mean to add as a dependency in a non Grails project? That is not supported at the moment, this is a Grails plugin only.
How to add this plugin to a Grails project should be covered by the Grails documentation at http://grails.github.io/grails-doc/latest/guide/plugins.html#creatingAndInstallingPlugins
