### ISSUE TITLE
IllegalArgumentException: Could not locate mail body 

### ISSUE THREAD

**Issue by kxt5258** [rlovtangen/grails-wkhtmltopdf#14]
I am getting some exceptions (java.lang.IllegalArgumentException) which I am not able to figure out. So basically I was following the steps mentioned in your documentation and when I call the action, I get the following exception (below ********)

The wkhtmltopdf has been installed and it is working when using from commandline. 

1) showDetails is a partial template
2) wkhtmltopdf version:  wkhtmltopdf:0.1.10
3) grails version: grails 2.4.4

---

Error 2016-01-04 16:14:58,707 [http-bio-8080-exec-3] ERROR errors.GrailsExceptionResolver  - IllegalArgumentException occurred when processing request: [GET] /packageName/my/downloadPDFTest/1234.pdf
Could not locate mail body /my/showDetails. Is it in a plugin? If so you must pass the plugin name in the [plugin] variable. Stacktrace follows:
Message: Could not locate mail body /my/showDetails. Is it in a plugin? If so you must pass the plugin name in the [plugin] variable
    Line | Method
->>  101 | createTemplate       in grails.plugin.mail.MailMessageContentRenderer

---

|     64 | doCall               in grails.plugin.mail.MailMessageContentRenderer$_render_closure1
|    180 | with . . . . . . . . in grails.plugin.mail.MailMessageContentRenderer$RenderEnvironment
|     63 | render               in grails.plugin.mail.MailMessageContentRenderer
|     67 | renderMailView . . . in org.wkhtmltox.WkhtmltoxService
|     42 | makePdf              in     ''
|     37 | makePdf . . . . . .  in     ''
|     42 | doCall               in WkhtmltopdfGrailsPlugin$_replaceRenderMethod_closure3
|    162 | $tt__downloadPDFTest in packageName.MyController
|    198 | doFilter             in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . . . . in grails.plugin.cache.web.filter.AbstractFilter
|   1145 | runWorker            in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run                  in java.lang.Thread

**Comment by rlovtangen** [comment]
Why is "packageName" part of the URL, is it the application name? 
Do you get the same error if you change the URL to .html instead of .pdf?

**Comment by kxt5258** [comment]
Yes  "packageName"  is appName.

With .html, I am getting NullPointerException

**Comment by rlovtangen** [comment]
Try to fix the NullPointerException and see if .pdf works then.

**Comment by kxt5258** [comment]
The issue was that I was using the view which has a different name from the action (or was it the partial template thing?). Once I renamed the view to have same name as action, it worked.

**Comment by rlovtangen** [comment]
:smile:
