### ISSUE TITLE
Invalid type of printMediaType attribute causing "--page-size specified in incorrect location"

### ISSUE THREAD

**Issue by sagrawal31** [rlovtangen/grails-wkhtmltopdf#19]
Data type of `printMediaType` should be `boolean` instead of `String` which is generating arguments as:

`[/usr/local/bin/wkhtmltopdf, --dpi, 260, --print-media-type, true, --page-size, A5, --zoom, 1.8, --encoding, UTF-8, --title, INV-00002, -q, -, -]`

But `--print-media-type` flag does not accept any value and hence causing `--page-size specified in incorrect location`.

**Comment by rlovtangen** [comment]
Released as 1.0.0.RC8
