### ISSUE TITLE
Don't replace the render method in the controller

### ISSUE THREAD

**Issue by ph4t** [rlovtangen/grails-wkhtmltopdf#5]
The plugin will replace the render method if contentType is "application/pdf". I can see how that is useful but how can it be disabled? I already have existing pdfs that need to be served, no need to regenerate them using this plugin.

**Comment by rlovtangen** [comment]
Not sure how to do that. It's only the one arg Map version of render that is replaced, maybe you could get around the problem with any of the other render methods. Or serve the existing pdfs as assets.
This was a design decision from before I forked the plugin. If you have any ideas of how to accommodate both needs, a pull request is very appreciated..

**Comment by rlovtangen** [comment]
Hope this solution works fine. I also merged the changes to the Grails 3 version.
