### ISSUE TITLE
Header doesn't work on Windows

### ISSUE THREAD

**Issue by ph4t** [rlovtangen/grails-wkhtmltopdf#6]
I'm trying to generate pdfs with a header using the following code. 

```
 def pdf = wkhtmltoxService.makePdf(
                view: "something",
                header: "/pdf/header",
                model: [
                         ...
                ],
                pageSize:"letter")
```

I get the following error on windows:

```
2015-08-12 10:28:40,318 [Thread-17] ERROR wkhtmltox.WkhtmltoxExecutor  - Error: Failed loading page http://file//C:\Users\****\AppData\Local\Temp\wkhtmltopdf6840842934454361668.html (sometimes it will work just to ignore this error with --load-error-handling ignore)
```

It seems to be related to https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1645. If wkhtmltopdf doesn't recognize the URL it will assume http... So, would it be possible not to specify "file://" prefix on windows?

**Comment by rlovtangen** [comment]
I'm not a Windows user myself, so help with fixing this is appreciated.
Are you using the Grails 2 or Grails 3 version?

**Comment by ph4t** [comment]
I'm using grails 2.

**Comment by rlovtangen** [comment]
Hope this solution works fine. Merged the changes to the Grails 3 version as well. Thanks.
